### ISSUE TITLE
Problem with Project API request

### ISSUE THREAD

**Issue by noname2023CP** [hellohq-io/hellohq.docs#121]
Hello together, we have a Problem with the Request of Projects in API.

But just With the request of Projects. Any of the other Requests are working without a Problem.

![grafik](https://github.com/hellohq-io/hellohq.docs/assets/141654306/1adb0c0c-4295-44a0-82e9-17cfaa18c080)

We alwas get the General Exception Error.

We use O365 Enterprise and the Screenshot is out of Excel. I get the Same Error if i use Power BI.

Thanks for Help

**Comment by Schaukelking** [comment]
Hey @noname2023CP 
Sorry for the late response, we were lacking some capacity due to the vacation season.

What exactly are you trying to do? 
It looks like you are getting all projects successfully from our api, correct? 
Then you are creating an excel out of the result? In which process step does the error appear?

**Comment by noname2023CP** [comment]
Hey @Schaukelking,

sorry for my late response. Last week i was on vacation.

We would like to create an Excel with all our projects.

In my first message the picture shows were the Error appears.

The tablechart in excel is not complete. 2023 is missing and we get the GeneralException Error.
