### ISSUE TITLE
How to get invoices in hellohq v2 API?

### ISSUE THREAD

**Issue by ZHC-integration** [hellohq-io/hellohq.docs#123]
Hi,

I noticed this invoices API is not available in v2:
<img width="557" alt="image" src="https://github.com/hellohq-io/hellohq.docs/assets/142300267/2045de92-c4d8-4afb-bce2-089bbab33f56">

Can you assist if there alternative to retrieve them from v2 API (https://develop.hellohq.io/swagger/index.html)?

**Comment by Schaukelking** [comment]
Hey! 
You are right, we dont have an extra invoice endpoint. You will be able to get all documents (including invoices) with the `/Documents` endpoint. 

Currently, since all is still in development, you have to get all documents and filter by documentType on your own. But we are already working on bringing back the api filtering from the v1. The request would look like this to get all invoices:

`v2/Documents?$filter=documentType eq 'Invoice'`

I will keep this thread open until the api filtering is working again. 

Kind regards
Patrick

**Comment by Schaukelking** [comment]
As soon as the filters work again, it will. You will be able to get all invoices created on or after the first of july with this:

` v2/Documents?$filter=DocumentType eq 'Invoice' and CreatedOn ge 2023-07-01`

**Comment by ZHC-integration** [comment]
Hi Patrick,

For the development purpose, I tried to get all documents but it seems some issues here:
https://develop.hellohq.io/v2/Documents

<img width="368" alt="image" src="https://github.com/hellohq-io/hellohq.docs/assets/142300267/1468b358-108f-4376-b12c-63fe8aa91ff6">

**Comment by Schaukelking** [comment]
How does your authorization look like? 

At first you have to call the POST 
`https://develop.hellohq.io/v2/Authenticate/Login`
Endpoint. WIth this body:

```
{
  "userName": "[username]",
  "password": "[password]",
  "backendCustomerId": [customerid]
}
```

Then you get a bearer token as response. This has to be the autorization code for every following request you send.

**Comment by ZHC-integration** [comment]
Yes, I am using this token for Auth.

It works for \v2\Companies but not on \v2\Documents

Did I miss any setup ?

**Comment by Schaukelking** [comment]
For me it is working fine, so i guess some data in your system is messed up. 

Our error message handling is not done yet. If you send me an email (you can see my address in my profile) with the url to your helloHQ system, i can try to debug it to find a reason for that.

**Comment by projektagent** [comment]
Hello, 

at current time we get this information. 

_Zhihao hat sich bei uns im Forum gemeldet und dass er keine Endpoints findet. Das liegt daran, dass euer Testsystem? Bertelsmann.hellohq.io  bisher nicht unserer BETA hinzugefügt wurde.
Unsere Entwicklung macht das gleich und ist auch per Mail mit Zhihao im Austausch. Danach kann er dann auch auf die Endpoints zugreifen._

please check this.

**Comment by ZHC-integration** [comment]
Hi @Schaukelking ,

Did your team already get a chance to implement the filter features like below?

 v2/Documents?$filter=DocumentType eq 'Invoice' and CreatedOn ge 2023-07-01

**Comment by Schaukelking** [comment]
No, i will update you. We currently have to evaluate technically if it is worth to hand out Endpoints for documentTypes like we had in the old api (would be v2/Invoices) or if the way we want to handle with via filtering by type is a better solution.

**Comment by ZHC-integration** [comment]
Hi @Schaukelking ,

Do you have the estimated timeline on when this change will be ready?

**Comment by Schaukelking** [comment]
I hope next week. We are currently prepairing a beta release for monday.
This needs most of our capacity. When this is done I will tackle this topic again. 

What is the exact case why you need this urgent? I hope you can continue your current development without this, since you can get all documents in a current time range and then filter by the type of the document on your side.
Since there are multiple topics regarding our development api, it would be good to have a prio list of your requests.

**Comment by ZHC-integration** [comment]
Hi @Schaukelking ,

We would like to bring the invoices to the backend system, so we need to pull all invoices by date.

After pulling this invoice, we would like to update the status so we won't pull in any duplicate invoices. Is this action can be done in v2 version?

By the way, I noticed https://develop.hellohq.io/v2/Documents?filter=DocumentType eq 'Invoice' and CreatedOn ge 2023-08-01 still didn't work. 

Error:
{"message": "Unauthorized or unexpected error"}

**Comment by Schaukelking** [comment]
Issue is resolved. 
https://beta.hellohq.io/v2/Documents?filter=DocumentType eq 'Invoice' and CreatedOn ge datetime'2023-08-01' works

**Comment by ZHC-integration** [comment]
@Schaukelking , I have this issue again. 

Can you have a look?

https://beta.hellohq.io/v2/Documents?filter=DocumentType eq 'Invoice' and CreatedOn ge datetime'2023-08-01'

Error:
{"message": "Unauthorized or unexpected error"}
