### ISSUE TITLE
Error when filtering for CustomField Dates

### ISSUE THREAD

**Issue by cgerlfunkenwerfer** [hellohq-io/hellohq.docs#136]
Hello together, 

When making the following API-Request:

GET  https://api.hellohq.io/v1/Companies?$expand=CustomFields&$filter=CustomFields/any(customField: customField/UpdatedOn ge 2023-10-17)

We are always getting the following error:
 [500] Oops! Sorry, something went wrong. Please contact us in our developer portal at https://developer.helloHQ.io so we can assist you.

What we are trying to achieve, is getting all the Companies, where a Custom Field changed since a specific Date. But whenever I try to filter by a Date of a nested Property, it fails. 

Do you have any information about that and can help?

**Comment by Schaukelking** [comment]
Hey @cgerlfunkenwerfer,
Sadly there is no way to filter the updateOn / createdOn of our customFields due to our database structure. Dynamic database fields require a complex structure which makes it hard to give them all functionallities that other fields have. 

Is your company in our beta environment?
If not:
All you currently can do is filtering by the updatedOn of a company. When you change a custom field, the relating entity is also updating.

**Comment by cgerlfunkenwerfer** [comment]
Hello @Schaukelking , 

Thanks for the quick response! In our tests, updating a custom field did not change the "UpdatedOn" field of the company - that's why we tried to get updated companies that way. 

Could it be, that if we change a custom field, it takes some time until the "UpdatedOn" on the Company changes? Or that there is any bug?

Thanks!

**Comment by Schaukelking** [comment]
Hey @cgerlfunkenwerfer sorry! Did not recognize that you answered. 

Important question: Do you use our beta environment? 

In our beta systems the updatedOn of a company does not update when a custom field gets edited. We will tackle this in the near future. 

In our non-beta systems this should work. 


Again sorry for the late response! 
Kind regards
