### ISSUE TITLE
How to use the Filter Query correctly

### ISSUE THREAD

**Issue by fisadd** [hellohq-io/hellohq.docs#138]
**Describe** 
I am not able to get the Filter Query to work properly. I am following the documentation on how to use the filter parameter but when it gets to be detailed about what I want to filter, I'm kinda lost. 
This is an example from the documentation: 
/v1/Companies?$filter=UpdatedOn ge 2018-01-26 
but if i'm using it exactly like this, i just get all companies ever. the dataset doesnt change whether i use the filter or not.
I tried to replace the spaces but nothing worked for me. 
I also tried to filter with the field Number in the endpoint /Projects but same issue. 
How to use the filter paramter correctly?

**Comment by monderino** [comment]
Hi @fisadd,

If you really use this filter: /v1/Companies?$filter=UpdatedOn ge 2018-01-26
I would expect that you get all of your companies, because this get all companies updated after the 26.1.18. Because the ge means greater equal.
If you want all companies updated today for example you need ?$filter=UpdatedOn ge 2023-10-26

The Number field is a string and not really a number. here you cannot use ge. You can use equal for example.
See here:
<img width="1351" alt="Screenshot 2023-10-26 at 09 11 58" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/82d374e1-c4c7-40c6-bed8-19c12921961a">

I hope this help you.

Best 
Sven
