### ISSUE TITLE
How to set CustomFields in plannedrevenue/Positions

### ISSUE THREAD

**Issue by BernhardGruender** [hellohq-io/hellohq.docs#174]
Hi all,
I am trying to update Positions in PlannedRevenues.
Everything is working fine except for setting the value of a customfield.
Can anyone help me to find the problem?

Here are the Paramters of my PUT Request (everything will be set correctly except the Customfield)
URL: https://api.hqlabs.de/v1/PlannedRevenues(6740)/Positions(36055)
Body
{
    "Text": "Text.Test",
    "Unit": "days",
    "Amount": 11.0,
    "BookingAccount": "8404",
    "CostCenter2": "83",
    "Tax": 19.0,
    "Price": 16.70000,
    "TotalPrice": 183.70,
    "TotalUnitPrice": 16.70000,
    "TotalVat": 34.9,
    "Interval": "Once",
    "CustomFields": [
        {
            "Name": "My Customfield",
            "Value": "My Customfield.Test",
        }
    ]
}

**Comment by BernhardGruender** [comment]
Hi Sven,
I tried it with the ID as well.
Best Bernhard

**Comment by monderino** [comment]
I checked our code.
Unfortunately, it is not possible to to it directly in this call.

But I added new endpoints for you. 
With this endpoints you get the related custom fields of the position and you can update them.

The endpoints will go online tomorrow and you can use them. But maybe they will not show directly in our documentation, because the update process of the documentation will take longer.

Here the endpoints:
<img width="1212" alt="Screenshot 2024-08-08 at 12 15 22" src="https://github.com/user-attachments/assets/bba97b3a-320d-4851-8b0c-0765353de2e9">

I hope this will fix your issues.

Best 
Sven

**Comment by BernhardGruender** [comment]
Hi Sven,
thank you for the prompt and perfect solution. I will test it tomorrow.
Best Bernhard

**Comment by BernhardGruender** [comment]
Hi Sven,

sorry for my late reaction! There seems to be a problem. When I send _https://api.hqlabs.de/v1/PlannedRevenues(6844)/Positions(36337)?$expand=CustomFields_ I receive Customfields but when I send _https://api.hqlabs.de/v1/PlannedRevenues(6844)/Positions(36337)/CustomFields_ I receive none.
Did I missunderstoud something?
Best Bernhard

**Comment by monderino** [comment]
Hey @BernhardGruender,

please tell me the domain of your helloHQ System. Then I can check it out.

Best Sven
