### ISSUE TITLE
Local host access

### ISSUE THREAD

**Issue by gromchen** [hellohq-io/hellohq.docs#25]
I couldn't find how to enable `localhost` (or any other domain) in the [docs](https://developer.hellohq.io/).
Could you please provide an example?

Postman works
<img width="633" alt="image" src="https://user-images.githubusercontent.com/828918/154340062-eed1c07d-ce8a-4417-a347-593da75cb6af.png">

Local host is not
<img width="551" alt="image" src="https://user-images.githubusercontent.com/828918/154340256-83e4d7c3-7c76-4916-ab8e-ee1cbc2819c6.png">
<img width="533" alt="image" src="https://user-images.githubusercontent.com/828918/154340295-0ba5d1b6-7e8b-4ae0-9bba-afcba13214c4.png">

**Comment by monderino** [comment]
Hi @gromchen,

I'm not sure what you mean by enable localhost?
I tried the call and it works for me. Can you please provide the domain of the HQ system you working on.

Thank you and best regards
Sven

**Comment by gromchen** [comment]
As you can see from the screenshot, I use `https://api.hqlabs.de/v1/Leads?$expand=CustomFields`

**Comment by gromchen** [comment]
Do you have an example repo so I could check on my side?

**Comment by monderino** [comment]
I'm not sure what you are try to do, but this is a rest api call and you can't use them in the browser, because you did't not send the Authorization Header. That is the reason why it works in Postman but not in you Browser.

**Comment by gromchen** [comment]
Please take a look at the screenshot once again at the bottom. I send the `Authorization` header with `Bearer ${token}`.
Could you please clarify whether it is possible to use API from the browser?

**Comment by monderino** [comment]
Can you explain how I can add the header in the browser? Then I can test it on our end.

**Comment by gromchen** [comment]
I tried to get through authorization flow with Postman and got the following 500 (I guess the same it was before)
```
[ArgumentException: Customer cannot be null (for api.hqlabs.de)]
   HQSB.Web.Utils.HQRequestContextStore.GetContext() in D:\a\hq-legacy\hq-legacy\HQSB.Web.Utils\HQRequestContextStore.cs:104
   HQSB.API.MvcApplication.Application_EndRequest(Object sender, EventArgs e) in D:\a\hq-legacy\hq-legacy\HQSB.API\Global.asax.cs:289
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +223
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +220
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +1361
```
Could you please clarify the error?

**Comment by monderino** [comment]
Sorry but, you give me too little information, so I just can't help you!
The Message tells you that we do not know who you are, because of missing or wrong information you send to us.

Have you an API Client created which you use for the OAuth flow? 
You need to do this in the HQ in the Admin => API Client section.

- It would be very helpful if you could tell me the customer you are working (The URL of your HQ is enough for me, example: test.hellohq.io) for.
- Which API client you use for the OAuth flow

In your previous examples, where do you get the token from?

**Comment by gromchen** [comment]
@monderino got you
Please check https://new-exeo.hellohq.io/login

**Comment by monderino** [comment]
Ok thanks, can you please answer my other questions.

**Comment by gromchen** [comment]
If I understand correctly, API Client should be `589166-HQ-Shyftplan`

**Comment by monderino** [comment]
Not sure if this will help you, because I don't know what you set in Postman, but here are my settings and get a token back.

Settings Postman:

<img width="573" alt="Screenshot 2022-02-21 at 14 22 08" src="https://user-images.githubusercontent.com/23459030/154963979-02541820-8f32-4558-bb51-d72f22c87960.png">

Result: 

<img width="846" alt="Screenshot 2022-02-21 at 14 23 17" src="https://user-images.githubusercontent.com/23459030/154964027-e642b2ca-5b60-4275-94f8-c6b458faec26.png">

**Comment by gromchen** [comment]
The token generated with Postman UI worked with the browser's `/Leads` endpoint. Thank you.
Now I need to figure out how to make the same token without Postman.

**Comment by gromchen** [comment]
It looks like the documentation is outdated.
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/828918/154969708-4d764433-c1a0-46fc-a74a-fd5b5e78132b.png">
Postman sent the following properties
<img width="396" alt="image" src="https://user-images.githubusercontent.com/828918/154970119-a6c95591-e93f-4f2f-be0c-4be320a38cce.png">
Specifically `client_id` and there is no base24 encoding.

Please update the documentation.

**Comment by monderino** [comment]
I don't know which kind of application you build... but is it necessary that every user login into this application?
If not you do not need to implement the OAuth flow, you can just use the token we provide you on Admin => API Clients. 
If you need a login of the exeo users, you need to implement the OAuth flow.

**Comment by gromchen** [comment]
Yes, we need login by a user because they'll have different roles.
