### ISSUE TITLE
filter projects on custom field

### ISSUE THREAD

**Issue by theresa-sporn** [hellohq-io/hellohq.docs#31]
**Describe**
I want to extract all projects that have "GPP: Ja" in their custom field (see screenshot 1). The seems to be some confusion with the ids. Using this API call gets me the wrong projects (see screenshot 2). I've tried everything I can think of but can't seem to get the correct outcome. 

**Additional context**
screenshot 1: 
![Screenshot 2022-05-05 at 13 15 29](https://user-images.githubusercontent.com/72218893/166912898-70daf677-4f02-464f-b424-35ef7b57f780.png)
screenshot 2: 
Removed

**Comment by monderino** [comment]
Hi @theresa-sporn 

I think you can fetch all projects with GPP : Ja with one call:
`https://api.hellohq.io/v1/Projects?$expand=CustomFields&$filter=CustomFields/any(cf: cf/Value eq 'Ja') and CustomFields/any(cf: cf/Name eq 'GPP') `

I remove your second screenshot because it includes sensitive data and this issue is public.

Best regards 
Sven

**Comment by theresa-sporn** [comment]
Amazing, it worked, thanks a lot!
