### ISSUE TITLE
Number of hours worked on projects per month per recruiter

### ISSUE THREAD

**Issue by theresa-sporn** [hellohq-io/hellohq.docs#43]
**Describe**
I am looking for a way to sum up all hours a person has worked on projects per month.

**Additional context**
I am thinking about merging the projects and users tables and summing up the hours worked but is there a direct way to find the number of hours?

**Comment by Schaukelking** [comment]
Hey Theresa (:

There is no direct way to get the number of worked hours of a user on a project. 

What you can do:

You can get all UserReportings for a project 
`https://api.hellohq.io/v1/UserReportings?$filter=ProjectId eq [ProjectId]`
and then sum all Durations for the same UserIds. 

You also can use one call to get all reportings for a user on the project
`https://api.hellohq.io/v1/UserReportings?$filter=ProjectId eq [ProjectId] and UserId eq [UserId]`
and than sum up the Duration.

I hope this helps you finalizing your task.

Best regards
Padsen

**Comment by Schaukelking** [comment]
Hey,

Sorry [ProjectId] and [UserId] are placeholders (: If you want all reportings according to a project with e.g. Id 14 from a user with id 1 the url would look like that:

`https://api.hellohq.io/v1/UserReportings?$filter=ProjectId eq 14 and UserId eq 1`

This call filters all UserReportings by project and user. This is what my example request is for. Is this helpful for what you try to do? I don't know what exactly the outcome shoule be. Do you want to do it for all users and all projects? Then i guess you have to collet all userreportings and then calculate manually, there is no such functionallity in our api (:

**Comment by theresa-sporn** [comment]
Ahhh okay makes sense, thank you!

**Comment by Schaukelking** [comment]
You're welcome!

**Comment by Schaukelking** [comment]
What are you using?

`v1/UserReportings?$filter=UserId eq 1` and `v1/Users({1})/Reportings` are doing the same. All calculations and groupings (projects, months) you have to do by your own.

**Comment by theresa-sporn** [comment]
I am trying to pass a list of user ids in the following api call but I keep getting errors:
`def get_users(user_ids):
    users = dict()
    for i in list(set(user_ids)):
        url = "https://api.hellohq.io/v1/UserReportings({})".format(i)
        headers = {
        'Authorization': 'Bearer xxx'}
        response = json.loads(requests.get(url, headers=headers).content.decode('utf-8'))
        #response = session.get(url, headers=headers).json()
        users.update({i: response})
    return users`

**Comment by Schaukelking** [comment]
When using `https://api.hellohq.io/v1/UserReportings({Id})` you have to pass a user reporting id , so you have like `https://api.hellohq.io/v1/UserReportings(123)`. If you want all reportings for users use as i mentioned `https://api.hellohq.io/v1/Users(1)/Reportings` or `https://api.hellohq.io/v1/UserReportings?$filter=UserId eq 1`

In my example is 123 the id of a user reporting and 1 an user id. I cannot help with the correct syntax because i don't know the language you're coding in but it seems like you want to pass the userids in the userreportings as id which will not work. And also remove the {}. I think this topic is closed now since I cannot provide more informations than what the endpoints returns back (:

**Comment by theresa-sporn** [comment]
Okay, thank you for your help, I will try to solve it!

**Comment by theresa-sporn** [comment]
I am coding in python by the way, as you can see in the code that I sent :)
