### ISSUE TITLE
How to make API for Leads get/add leads

### ISSUE THREAD

**Issue by shubhamwebdeveloper** [hellohq-io/hellohq.docs#49]
Hi team

Please help me as per document not working Leads GET/POST leads API
**getting Error: response status is 500**
https://watch.screencastify.com/v/JW5fPoS2l6x03ByhKdJ0

curl --location --request GET 'https://api.hqlabs.de/v1/Leads' \
--header 'Content-Type: application/json' \
--header 'accept: application/json' \
--header 'Authorization: Bearer jr_QruCg8Hz8RRhSQwieDG8pEXM9MuraOKnAw2-rfIMO4dZQcG2r-iZfPkLvK5QH16ne4LWOEl-8-lgomIe0_evpe26OLS3MX_T-i8yJJHU51o42JclgHmIQQX2Jvk3obq8gXzGQ5P6BqakW2KdOK3E1TIAmcVe2kXjnKm2_k0XaP-iYEY_4Ygm9QCe1hJ1L08T1H78Aupb9sI6YB1ZSUaV0ly4dcNmjUFPJoMvcfBL9Sdf4SUgltBGgqKMAFK3V'

**Comment by monderino** [comment]
Hi @shubhamwebdeveloper ,

I updated your post because of the token. This is a puplic area, please never put secure information in your posts. Thank you.

I tested the call and for me it is working.
`curl --request GET \
  --url https://api.hqlabs.de/v1/Leads \
  --header 'Authorization: Bearer jr_QruCg8Hz....'`
