### ISSUE TITLE
Pagination not working on PlannedRevenues 

### ISSUE THREAD

**Issue by chrgruber** [hellohq-io/hellohq.docs#5]
**Describe the bug**
As described previously the API should only return a maximum of 1000 elements per request. This is not true for the PlannedRevenues call, though. It returns the full amount of items. With a paginated request all items above the 1000 mark will be doubled.

**To Reproduce**
1. https://api.hqlabs.de/v1/PlannedRevenues?$skip=0
2. ~1.350 elements
3. https://api.hqlabs.de/v1/PlannedRevenues?$skip=1000
4. ~350 elements

**Expected behavior**
Request should only return 1000 items max

**Comment by monderino** [comment]
Hi @chrgruber,

can you tell me for which HQ customer you do the calls?

Best regards
Sven

**Comment by chrgruber** [comment]
Hi @monderino,
it's mediawave commerce GmbH

Best regards,
Christoph

**Comment by monderino** [comment]
Hi Christopher,

sorry for the long waiting time. The endpoints related to documents (planned revenues, invoices, quotations, etc) are a bit special. Here we do not have a max page size, because of technical reasons. That means you get always all Data if you not use skip and take.

Best regards,
Sven
