### ISSUE TITLE
/v1/Me endpoint not working

### ISSUE THREAD

**Issue by jon-ovan** [hellohq-io/hellohq.docs#55]
It returns a 404 Not Found.

**Comment by Schaukelking** [comment]
Hey jon,

how is your procedure until then? You'll need to authenticate your user before calling this endpoint via OAuth. I know you have currently struggle with that but there is no other way to get the Me endpoiunt running. It returns 404 because the endpoint does not know which user to return.

Kind regards
Padsen

**Comment by jon-ovan** [comment]
Hi Padsen, I do a GET to https://api.hellohq.io/v1/Me with a valid header Authentication Bearer token.
Do I need to pass an id as well as parameter? I assumed it was okay with no id since the documentation provides both options.

Thanks.
Jon

**Comment by Schaukelking** [comment]
The bearer token allows you to use the api but with no specific user. So "Me" will never return a user.

You can get all Users by the "/Users" endpoint, or a specific user with "/Users(UserId)". When your user verified himself via oauth it will return the verified user. Until then "/Me" will not work.

**Comment by jon-ovan** [comment]
I understand now, thanks for the clarification!! 😄

**Comment by Schaukelking** [comment]
You are welcome! (:
