### ISSUE TITLE
How to filter any field using the APIs filter functionality

### ISSUE THREAD

**Issue by OrtiMussPrime** [hellohq-io/hellohq.docs#62]
Hi, I would like to use the filter functionality to filter for specific fields in the request.
As far as I understood it is possible to filter serverside instead of clientside for specific information.

When it comes to the example in your docs for filtering for a company type by its ID this example is given:
`v1/Companies?$expand=CompanyTypes&$filter=CompanyTypes/any(companyType: companyType/Id eq 4002)`

In my understanding the query is built something like this:
`v1/Route?expand=PropertyToBeExpanded&$filter=PropertyToBeExpanded/filterType(property: property/sub-property eq value)`

How would that translate to filtering projects by their number?
For example I do a query on `/v1/Projects` and want to have a project with the NUMBER (not ID) 2202.

Additionally, if I understood correctly you can also expand related entities on the query - which would mean it should also be possible to get all tasks related to the project within the same query right? How would this query look like?

**Comment by Schaukelking** [comment]
Hello!

Sorry for the late response! We're quiet busy at the moment.

The filtering you got there is only for related properties, so properties you only get via expanding. 
Your request for filtering by project number is way simpler:
`https://api.hellohq.io/v1/Projects?$filter=Number eq '2202'`  since Number is a string peroperty of the Project entity. 

I guess this is what you are looking for? You can have a look on the first exmaple of the filter section in the [developer guide](https://developer.hellohq.io/). 

Since ProjectTasks are not part of the Project model you will not be able to get them via expand. Sorry for that. 

If you want to get all tasks for a project via number instead of Id you can use the following request:
`https://api.hellohq.io/v1/ProjectTasks?$expand=Project&$filter=Project/Number eq '2202'`

Here you request all ProjectTasks, expanding the project and filtering by Number. So you just get tasks where the according Project has the number 2202. If you have the ID you can have it simpler:
`https://api.hellohq.io/v1/ProjectTasks?$filter=ProjectId eq [ID]`

Hope this answers your question, if not let me know!
Best Regards,
Patrick

**Comment by OrtiMussPrime** [comment]
Hello @Schaukelking thanks for your response.
Yes that was what I was looking for.

Is there an overview on the expand model, on how it can be used and works or what is related to what? I currently find hard to grasp the concept behind it. 

> Here you request all ProjectTasks, expanding the project and filtering by Number.
Is that for all entities like this that the "subcategory" gets expanded by the main entity?
As I explained forehand, it is hard to understand the correct way to expand and filter just from the examples.

**Comment by Schaukelking** [comment]
Hello! 

You can find all related entities in the response model of the entity you are requesting. 
![image](https://user-images.githubusercontent.com/48789562/201870543-7f6e692b-d0f9-4b77-b56a-160ee69da204.png)

I marked two examples from the Get ProjectTask response model. Since they are extra entities, you have to expand them by hand. This is where the expand part is important. 

> v1/Route?expand=PropertyToBeExpanded&$filter=PropertyToBeExpanded/filterType(property: property/sub-property eq value)

This is already correct, but only for collections. So if you have multiple instances of the entity linked. Since a ProjectTask can only have one project i filtered the Project by Number like this

`v1/Route?expand=PropertyToBeExpanded&$filter=PropertyToBeExpanded/sub-property eq value`

So just without your "filterType" stuff of the example. But in general you understood it correctly!

**Comment by OrtiMussPrime** [comment]
Thanks a lot, that clarifies already many things. Do you have another concrete example for me with the "filterType" that I mentioned, because I think it would even clarify a lot of things for me.

**Comment by Schaukelking** [comment]
Example:
https://api.hellohq.io/v1/ProjectTasks?$expand=Assignments&$filter=Assignments/any(assignment: assignment/UserId eq 1)

Gets all ProjecetTasks where the user with the id 1 is assignet to. Assignment**s** is a list. We check if any assignment has a UserId of 1.

So my operation is any -> "assignment" is the single instance of the list where i check if the instance has a userid of 1.

**Comment by OrtiMussPrime** [comment]
Thanks a lot for your help, this definitely helped me to understand your api better. Maybe you guys should add a description like this to your API docs, I think it might be helpful for more people in the future.

> v1/Route?expand=PropertyToBeExpanded&$filter=PropertyToBeExpanded/filterType(property: property/sub-property eq value)
