### ISSUE TITLE
API from HQ to "workflow" and "datastudio" are not working anymore :(

### ISSUE THREAD

**Issue by OlafHeinrich** [hellohq-io/hellohq.docs#67]
**Describe the bug**

Dear HQ team,
The point is that recently our HQ API stopped working:
First, data cannot be retrieved from HQ and displayed in Data Studio anymore(Fehler 502).
On the other hand, data from "Workflow" (our ordering tool) is now not sent to HQ (Fehler 502).
There is currently an error message in detail:

Access to XMLHttpRequest at 'https://api.upljft.com/v1/workflow/freelance-request' from origin 'https://workflow.upljft.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**To Reproduce**
The URL to the HQ API CLIENT Settings:
https://upljft.hellohq.io/hqframe?menuitemid=24144&url=admin_client

**Expected behavior**
For "datastudio" we expect that the data from HQ will sync to datastudio
for the "workflow API" we expect that our tool "workflow" can generate orders in HQ-Projects and read Project- and Client informations out of HQ. In the past both API works, we are not sure why it actually didn´t work. 

**Screenshots**
![Bildschirmfoto 2022-12-01 um 11 17 01](https://user-images.githubusercontent.com/119044540/205027821-2ac7436c-a667-469e-a89e-a032b6ecb899.png)
![Bildschirmfoto 2022-12-01 um 11 19 52](https://user-images.githubusercontent.com/119044540/205027825-8fa204a8-18ad-4fa0-a7d5-4cc3514cb2e5.png)

**Environment (please complete the following information):**
 - macOS Monterey 12.6.1
 - Browser: Chrome
 - Version 107.0.5304.110 (Offizieller Build) (arm64)

We would be very thankfull for help :)
Olaf
Upljft GmbH

**Comment by monderino** [comment]
Hi, 
Sorry I updated your comment and removed one image. Because you showed secure values in it.

**Comment by monderino** [comment]
Hi @OlafHeinrich ,

I'm actually not sure if we are able to help you here. Because I don't think that our API is involved. 
I tested our API with all tokens and it worked. 

I guess the communication between api.upljft.com and workflow.uplfjt.com isn't working. But this is only an idea, without having any idea about your process behinfd

I found this article, maybe it will help you.
https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe

If you have more information or I can help you further, please let me know.

Best regards
Sven
